/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'UserSignup': ApiRouteHandler<{ email: string; password: string; name: string }, ApiResponse<201, { id: string; email: string; name: string; createdAt: string }> | ApiResponse<400, { error: string }>, never>
    'ScheduledAnalytics': CronHandler<never>
    'RetryHandler': EventHandler<{ taskId: string; error: string; retryCount?: number }, never>
    'GetEntities': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { posts: Array<{ id: string; title: string; content: string; authorId: string; createdAt: string }>; count: number }>, never>
    'CreateEntity': ApiRouteHandler<{ title: string; content: string; authorId: string }, ApiResponse<201, { id: string; title: string; content: string; authorId: string; createdAt: string }> | ApiResponse<400, { error: string }>, { topic: 'entity.created'; data: { entityId: string; entityType: string; authorId: string } }>
    'BackgroundProcessor': EventHandler<{ entityId: string; entityType: string; authorId: string }, never>
    'ProductCatalog': ApiRouteHandler<{ name: string; price: number; description: string; stock: unknown }, ApiResponse<201, { id: string; name: string; price: number }>, never>
    'OrderProcessing': ApiRouteHandler<{ items: Array<{ productId: string; quantity: number }>; customerId: string }, ApiResponse<201, { orderId: string; status: string; total: number }>, never>
    'StateAuditJob': CronHandler<{ topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'ProcessFoodOrder': EventHandler<{ email: string; quantity: number; petId: string }, { topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'Notification': EventHandler<{ templateId: string; email: string; templateData: Record<string, unknown> }, never>
    'ApiTrigger': ApiRouteHandler<{ pet: { name: string; photoUrl: string }; foodOrder?: { quantity: number } }, ApiResponse<200, { id: string; name: string; photoUrl: string }>, { topic: 'process-food-order'; data: { email: string; quantity: number; petId: string } }>
    'WorkflowRegistrar': EventHandler<{ workflows: Array<{ name: string; enabled: boolean; customization: { entities: Array<string>; features: Array<string> } }>; endpoints: Array<string>; endpointDetails: Array<{ method: string; path: string; workflow: string; description: string }>; backendId: string; traceId: string }, { topic: 'workflows.registered'; data: { backendId: string; metadata: { id: string; workflows: Array<unknown>; endpoints: Array<string>; endpointDetails: Array<unknown>; createdAt: string; status: string }; traceId: string } }>
    'WorkflowAssembler': EventHandler<{ template: { name: string; workflows: Array<string>; endpoints: Array<{ method: string; path: string; workflow: string; description: string }> }; entities: Array<string>; features: Array<string>; backendId: string; traceId: string }, { topic: 'workflows.assembled'; data: { workflows: Array<{ name: string; enabled: boolean; customization: { entities: Array<string>; features: Array<string> } }>; endpoints: Array<string>; endpointDetails: Array<{ method: string; path: string; workflow: string; description: string }>; backendId: string; traceId: string } }>
    'TemplateSelector': EventHandler<{ entities: Array<string>; features: Array<string>; templateType: string; originalDescription: string; backendId: string; traceId: string }, { topic: 'template.selected'; data: { template: { name: string; workflows: Array<string>; endpoints: Array<{ method: string; path: string; workflow: string; description: string }> }; entities: Array<string>; features: Array<string>; backendId: string; traceId: string } }>
    'ForgeBackendApi': ApiRouteHandler<{ description: string }, ApiResponse<200, { backendUrl: string; endpoints: Array<string>; backendId: string }> | ApiResponse<400, { error: string }>, { topic: 'project.description.received'; data: { description: string; backendId: string; traceId: string } }>
    'CloudDeployer': EventHandler<{ backendId: string; metadata: { id: string; workflows: Array<unknown>; endpoints: Array<string>; endpointDetails: Array<unknown>; createdAt: string; status: string }; traceId: string }, never>
    'AIIntentParser': EventHandler<{ description: string; backendId: string; traceId: string }, { topic: 'intent.parsed'; data: { entities: Array<string>; features: Array<string>; templateType: string; originalDescription: string; backendId: string; traceId: string } }>
  }
    
}